[versions]
agp = "8.5.0"
kotlin = "2.0.20"
android-minSdk = "24"
android-compileSdk = "34"
dokka = "1.9.20"
kotlinxSerializationJson = "1.7.3"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }